In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("train.csv",header=0)

In [3]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
from sklearn.preprocessing import LabelEncoder
data.Embarked=LabelEncoder().fit_transform(data.Embarked)

In [5]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,2

In [6]:
data.Sex=LabelEncoder().fit_transform(data.Sex)

In [7]:
data["Survived"].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [14]:
trainx=data.drop(['Survived','Name','Ticket','Cabin'],axis=1)

In [9]:
trainy=data[['PassengerId','Survived']]

In [10]:
trainy.head()

   PassengerId  Survived
0            1         0
1            2         1
2            3         1
3            4         1
4            5         0

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [12]:
log_reg=LogisticRegression()
rnd_clf=RandomForestClassifier()
svm_clf=SVC()

voting_clf=VotingClassifier(
    estimators=[('lr',log_reg), ('rf', rnd_clf), ('svc', svm_clf)], 
    voting='hard')

In [13]:
voting_clf.fit(trainx, trainy)

ValueError: y should be a 1d array, got an array of shape (891, 2) instead.