In [1]:
import numpy as np
import pandas as pd

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [3]:
train.head()

,id,allelectrons_Total,density_Total,allelectrons_Average,val_e_Average,atomicweight_Average,ionenergy_Average,el_neg_chi_Average,R_vdw_element_Average,R_cov_element_Average,zaratio_Average,density_Average,Hardness
0,0,100.0,0.841611,10.0,4.8,20.612526,11.08810,2.766,1.732,0.860,0.496070,0.91457,6.0
1,1,100.0,7.558488,10.0,4.8,20.298893,12.04083,2.755,1.631,0.910,0.492719,0.71760,6.5
2,2,76.0,8.885992,15.6,5.6,33.739258,12.08630,2.828,1.788,0.864,0.481478,1.50633,2.5
3,3,100.0,8.795296,10.0,4.8,20.213349,10.94850,2.648,1.626,0.936,0.489272,0.78937,6.0
4,4,116.0,9.577996,11.6,4.8,24.988133,11.82448,2.766,1.682,0.896,0.492736,1.86481,6.0

In [4]:
trainx=train.drop(['id','Hardness'],axis=1)

In [5]:
trainy=train['Hardness']

In [6]:
train.isnull().sum()

id                       0
allelectrons_Total       0
density_Total            0
allelectrons_Average     0
val_e_Average            0
atomicweight_Average     0
ionenergy_Average        0
el_neg_chi_Average       0
R_vdw_element_Average    0
R_cov_element_Average    0
zaratio_Average          0
density_Average          0
Hardness                 0
dtype: int64

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
reg=LinearRegression().fit(trainx,trainy)

In [9]:
testx=test.drop('id',axis=1)

In [10]:
prediction=reg.predict(testx)

In [11]:
prediction=prediction.round(3)

In [12]:
testy=pd.DataFrame(prediction)

In [13]:
testy['id']=test['id']

In [14]:
testy.head()

       0     id
0  3.478  10407
1  4.836  10408
2  5.284  10409
3  5.276  10410
4  5.095  10411

In [16]:
testy.to_csv('subm.csv')

In [17]:
testy.head()

       0     id
0  3.478  10407
1  4.836  10408
2  5.284  10409
3  5.276  10410
4  5.095  10411